workflow:
    rules:
        -
            if: "$CI_PIPELINE_SOURCE == 'merge_request_event'"
        -
            if: $CI_COMMIT_TAG
        -
            if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
stages:
    - code-quality
code-quality:
    parallel:
        matrix:
            -
                php_version:
                    - '8.1'
                    - '8.2'
                typo3_version:
                    - '11.5'
                    - '12.4'
    before_script:
        - 'set -xe'
        - 'apt-get update -yqq'
        - 'apt-get install git libzip-dev unzip parallel libxml2-utils wget wait-for-it libicu-dev -yqq'
        - 'php -r "readfile(''http://getcomposer.org/installer'');" | php -- --install-dir=/usr/local/bin/ --filename=composer'
        - 'chmod +x /usr/local/bin/composer'
        - 'composer config cache-dir ./cache/composer'
        - 'cp /usr/local/etc/php/php.ini-production /usr/local/etc/php/php.ini'
        - 'awk ''/^error_reporting = E_ALL/{print "error_reporting = E_ALL & ~E_DEPRECATED"; next}1'' /usr/local/etc/php/php.ini > temp.ini && mv temp.ini /usr/local/etc/php/php.ini'
        - 'composer require typo3/cms-core ^${typo3_version} --no-progress --ignore-platform-req=ext-intl'
        - 'composer install --no-progress --ignore-platform-req=ext-intl'
    image: 'php:${php_version}'
    stage: code-quality
    script:
        - 'composer ci'
