services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  DigitalMarketingFramework\Typo3\Core\:
    resource: '../Classes/*'

  DigitalMarketingFramework\Typo3\Core\Controller\ConfigurationDocumentAjaxController:
    public: true

  # backend module controllers
  DigitalMarketingFramework\Typo3\Core\Controller\EventListener\BackendControllerUpdateEventListener:
    tags:
      - name: event.listener
        identifier: 'digital-marketing-framework/core/backend-controller/update'
        event: DigitalMarketingFramework\Typo3\Core\Controller\Event\BackendControllerUpdateEvent

  # static configuration document update
  DigitalMarketingFramework\Typo3\Core\ConfigurationDocument\Storage\EventListener\StaticConfigurationDocumentIdentifierCollectionEventListener:
    tags:
      - name: event.listener
        identifier: 'digital-marketing-framework/core/static-configuration-document/collect-identifiers'
        event: DigitalMarketingFramework\Typo3\Core\ConfigurationDocument\Storage\Event\StaticConfigurationDocumentIdentifierCollectionEvent

  DigitalMarketingFramework\Typo3\Core\ConfigurationDocument\Storage\EventListener\StaticConfigurationDocumentLoadEventListener:
    tags:
      - name: event.listener
        identifier: 'digital-marketing-framework/core/static-configuration-document/load'
        event: DigitalMarketingFramework\Typo3\Core\ConfigurationDocument\Storage\Event\StaticConfigurationDocumentLoadEvent

  # registry updates
  DigitalMarketingFramework\Typo3\Core\Registry\EventListener\CoreRegistryGlobalConfigurationUpdateEventListener:
    tags:
      - name: event.listener
        identifier: 'digital-marketing-framework/core/registry-update/core/global-configuration'
        event: DigitalMarketingFramework\Typo3\Core\Registry\Event\CoreRegistryGlobalConfigurationUpdateEvent

  DigitalMarketingFramework\Typo3\Core\Registry\EventListener\CoreRegistryServiceUpdateEventListener:
    tags:
      - name: event.listener
        identifier: 'digital-marketing-framework/core/registry-update/core/service'
        event: DigitalMarketingFramework\Typo3\Core\Registry\Event\CoreRegistryServiceUpdateEvent

  DigitalMarketingFramework\Typo3\Core\Registry\EventListener\CoreRegistryPluginUpdateEventListener:
    tags:
      - name: event.listener
        identifier: 'digital-marketing-framework/core/registry-update/core/plugin'
        event: DigitalMarketingFramework\Typo3\Core\Registry\Event\CoreRegistryPluginUpdateEvent
