services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  DigitalMarketingFramework\Typo3\Core\:
    resource: '../Classes/*'

  # REST API
  DigitalMarketingFramework\Typo3\Core\Middleware\RestMiddleware:
    public: true

  DigitalMarketingFramework\Typo3\Core\Controller\ConfigurationDocumentAjaxController:
    public: true

  # backend module controllers
  DigitalMarketingFramework\Typo3\Core\Controller\EventListener\BackendControllerUpdateEventListener:
    tags:
      - name: event.listener
        event: DigitalMarketingFramework\Typo3\Core\Controller\Event\BackendControllerUpdateEvent

  # static configuration document update
  DigitalMarketingFramework\Typo3\Core\ConfigurationDocument\Storage\EventListener\CoreSystemConfigurationDocumentEventListener:
    tags:
      - name: event.listener
        event: DigitalMarketingFramework\Typo3\Core\ConfigurationDocument\Storage\Event\StaticConfigurationDocumentIdentifierCollectionEvent
      - name: event.listener
        event: DigitalMarketingFramework\Typo3\Core\ConfigurationDocument\Storage\Event\StaticConfigurationDocumentLoadEvent

  DigitalMarketingFramework\Typo3\Core\ConfigurationDocument\Storage\EventListener\CoreStaticConfigurationDocumentEventListener:
    tags:
      - name: event.listener
        event: DigitalMarketingFramework\Typo3\Core\ConfigurationDocument\Storage\Event\StaticConfigurationDocumentIdentifierCollectionEvent
      - name: event.listener
        event: DigitalMarketingFramework\Typo3\Core\ConfigurationDocument\Storage\Event\StaticConfigurationDocumentLoadEvent

  # registry updates
  DigitalMarketingFramework\Typo3\Core\Registry\EventListener\CoreRegistryUpdateEventListener:
    tags:
      - name: event.listener
        event: DigitalMarketingFramework\Typo3\Core\Registry\Event\CoreRegistryUpdateEvent

  # frontend scripts updates
  DigitalMarketingFramework\Typo3\Core\Api\EventListener\FrontendJavaScriptUpdateEventListener:
    tags:
      - name: event.listener
        event: DigitalMarketingFramework\Typo3\Core\Api\Event\FrontendJavaScriptUpdateEvent
