services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  DigitalMarketingFramework\Typo3\Core\:
    resource: '../Classes/*'

  DigitalMarketingFramework\Typo3\Core\Tca\:
    resource: '../Classes/Tca/*'
    public: true

  DigitalMarketingFramework\Typo3\Core\Controller\BackendModuleController:
    tags: ['backend.controller']

  # registry collection
  DigitalMarketingFramework\Typo3\Core\Registry\RegistryCollection:
    public: true

  DigitalMarketingFramework\Typo3\Core\Registry\EventListener\RegistryCollectionEventListener:
    tags:
      - name: event.listener
        event: DigitalMarketingFramework\Typo3\Core\Registry\RegistryCollection

  # registry
  DigitalMarketingFramework\Typo3\Core\Registry\EventListener\CoreRegistryUpdateEventListener:
    tags:
      - name: event.listener
        event: DigitalMarketingFramework\Typo3\Core\Registry\Event\CoreRegistryUpdateEvent

  # REST API
  DigitalMarketingFramework\Typo3\Core\Middleware\RestMiddleware:
    public: true
